name: Cobertura

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restaurar dependências
        run: dotnet restore
      - name: Instalar dotnet-coverage
        run: dotnet tool install --global dotnet-coverage
      - name: Executar testes com cobertura
        run: |
          export PATH="$PATH:$HOME/.dotnet/tools"
          dotnet-coverage collect --output coverage.cobertura.xml --format cobertura -- dotnet test --no-build
      - name: Publicar artefatos
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.cobertura.xml
