name: Cobertura por Arquivo

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restaurar dependências
        run: dotnet restore
      - name: Executar testes com cobertura
        run: dotnet test --no-build --collect:"XPlat Code Coverage" --results-directory TestResults
      - name: Instalar ReportGenerator
        run: dotnet tool install --global dotnet-reportgenerator-globaltool
      - name: Gerar relatório em Markdown
        run: |
          export PATH="$PATH:$HOME/.dotnet/tools"
          reportgenerator -reports:"TestResults/**/coverage.cobertura.xml" -targetdir:CoverageReport -reporttypes:MarkdownSummaryGithub
          cat CoverageReport/SummaryGithub.md >> $GITHUB_STEP_SUMMARY
      - name: Publicar artefatos
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: CoverageReport
