name: .NET CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test with coverage
      run: dotnet test --no-build --collect:"XPlat Code Coverage" --results-directory TestResults

    - name: Install ReportGenerator
      run: dotnet tool install --global dotnet-reportgenerator-globaltool

    - name: Generate coverage summary
      run: |
        export PATH="$PATH:$HOME/.dotnet/tools"
        reportgenerator -reports:"TestResults/**/*.cobertura.xml" -targetdir:CoverageReport -reporttypes:TextSummary
        cat CoverageReport/Summary.txt
