# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore PocLogs.sln
    - name: Build
      run: dotnet build PocLogs.sln --no-restore
    - name: Test
      run: dotnet test PocLogs.sln --no-build --verbosity normal --collect:"XPlat Code Coverage"
    - name: Generate coverage report
      run: |
        dotnet tool install --global dotnet-reportgenerator-globaltool
        reportgenerator -reports:**/coverage.cobertura.xml -targetdir:coveragereport -reporttypes:TextSummary
        cat coveragereport/Summary.txt
    - name: Publish AOT
      run: dotnet publish PocLogs.Api/PocLogs.Api.csproj -c Release -r linux-x64 /p:PublishAot=true
